// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	book "api/features/book"

	mock "github.com/stretchr/testify/mock"
)

// BookData is an autogenerated mock type for the BookData type
type BookData struct {
	mock.Mock
}

// Add provides a mock function with given fields: userID, newBook
func (_m *BookData) Add(userID int, newBook book.Core) (book.Core, error) {
	ret := _m.Called(userID, newBook)

	var r0 book.Core
	if rf, ok := ret.Get(0).(func(int, book.Core) book.Core); ok {
		r0 = rf(userID, newBook)
	} else {
		r0 = ret.Get(0).(book.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, book.Core) error); ok {
		r1 = rf(userID, newBook)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: bookID, updatedData
func (_m *BookData) Update(bookID int, updatedData book.Core) (book.Core, error) {
	ret := _m.Called(bookID, updatedData)

	var r0 book.Core
	if rf, ok := ret.Get(0).(func(int, book.Core) book.Core); ok {
		r0 = rf(bookID, updatedData)
	} else {
		r0 = ret.Get(0).(book.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, book.Core) error); ok {
		r1 = rf(bookID, updatedData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBookData interface {
	mock.TestingT
	Cleanup(func())
}

// NewBookData creates a new instance of BookData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBookData(t mockConstructorTestingTNewBookData) *BookData {
	mock := &BookData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
