// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// BookHandler is an autogenerated mock type for the BookHandler type
type BookHandler struct {
	mock.Mock
}

// Add provides a mock function with given fields:
func (_m *BookHandler) Add() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

// Update provides a mock function with given fields:
func (_m *BookHandler) Update() echo.HandlerFunc {
	ret := _m.Called()

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func() echo.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

type mockConstructorTestingTNewBookHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewBookHandler creates a new instance of BookHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBookHandler(t mockConstructorTestingTNewBookHandler) *BookHandler {
	mock := &BookHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
